apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./install.yml"
configMapGenerator:
  - name: db-cm0
    files:
      - ./data/config/initdb/grafana.sql
      - ./data/config/initdb/juno.sql
  - name: juno-admin-cm0
    files:
      - ./data/config/juno/entry.sh
      - ./data/config/juno/install.toml
      - ./data/config/juno/juno-grafana.ini
      - ./data/config/juno/juno-prometheus.yml
      - ./data/config/juno/multiple-region-admin.toml
      - ./data/config/juno/multiple-region-proxy.toml
      - ./data/config/juno/single-region-admin.toml
      - ./data/config/grafana/init_plugin.py
  - name: juno-agent-cm0
    files:
      - ./data/config/juno-agent/config.toml
  - name: pyroscope-cm0
    files:
      - ./data/config/pyroscope/server.yml
generatorOptions:
  disableNameSuffixHash: true
