apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "./install.yml"
configMapGenerator:
  - name: db-cm0
    files:
      - ./data/config/initdb/grafana.sql
      - ./data/config/initdb/juno.sql
generatorOptions:
  disableNameSuffixHash: true