package respGovern

type AppConfig struct {
	RuntimeStats
	JupiterRocketmqTestConsumerRwTimeout     string   `json:"jupiter.rocketmq.test.consumer.rwTimeout"`
	JupiterRestyTestCloseConnection          bool     `json:"jupiter.resty.test.closeConnection"`
	AppRegistryEtcdTimeout                   string   `json:"app.registry.etcd.timeout"`
	JupiterGrpcTestLevel                     string   `json:"jupiter.grpc.test.level"`
	JupiterDyrpcTestPassword                 string   `json:"jupiter.dyrpc.test.password"`
	JupiterBigmapTestDebug                   bool     `json:"jupiter.bigmap.test.debug"`
	JupiterRedixTestStubDialTimeout          string   `json:"jupiter.redix.test.stub.dialTimeout"`
	JupiterRestyTestRetryCount               int      `json:"jupiter.resty.test.retryCount"`
	JupiterMysqlGRPCAdminDebug               bool     `json:"jupiter.mysql.gRPCAdmin.debug"`
	AppMetricAddr                            string   `json:"app.metric.addr"`
	JupiterGrpcTestTimeout                   string   `json:"jupiter.grpc.test.timeout"`
	JupiterRocketmqTestConsumerGroup         string   `json:"jupiter.rocketmq.test.consumer.group"`
	JupiterMysqlGRPCAdminMaxIdleConns        int      `json:"jupiter.mysql.gRPCAdmin.maxIdleConns"`
	JupiterRocketmqTestConsumerSubExpression string   `json:"jupiter.rocketmq.test.consumer.subExpression"`
	JupiterRocketmqTestProducerTopic         string   `json:"jupiter.rocketmq.test.producer.topic"`
	JupiterMysqlGRPCAdminDsn                 string   `json:"jupiter.mysql.gRPCAdmin.dsn"`
	JupiterEtcdv3RegisterEndpoints           []string `json:"jupiter.etcdv3.register.endpoints"`
	JupiterMongoTestSocketTimeout            string   `json:"jupiter.mongo.test.socketTimeout"`
	JupiterRocketmqTestProducerGroup         string   `json:"jupiter.rocketmq.test.producer.group"`
	JupiterDyrpcEtcdHeaderTimeout            string   `json:"jupiter.dyrpc.etcd.headerTimeout"`
	JupiterRestyTestRetryMaxWaitTime         string   `json:"jupiter.resty.test.retryMaxWaitTime"`
	JupiterRestyTestDebug                    bool     `json:"jupiter.resty.test.debug"`
	JupiterRocketmqTestAddr                  []string `json:"jupiter.rocketmq.test.addr"`
	JupiterRocketmqTestConsumerEnable        bool     `json:"jupiter.rocketmq.test.consumer.enable"`
	JupiterRestyTestEnableMetric             bool     `json:"jupiter.resty.test.enableMetric"`
	JupiterRocketmqTestConsumerDialTimeout   string   `json:"jupiter.rocketmq.test.consumer.dialTimeout"`
	JupiterRestyTestTimeout                  string   `json:"jupiter.resty.test.timeout"`
	JupiterRedixTestStubMaxIdle              int      `json:"jupiter.redix.test.stub.maxIdle"`
	JupiterRedixTestStubIdleTimeout          string   `json:"jupiter.redix.test.stub.idleTimeout"`
	JupiterRestyTestSlowThreshold            string   `json:"jupiter.resty.test.slowThreshold"`
	JupiterMysqlGRPCAdminLevel               string   `json:"jupiter.mysql.gRPCAdmin.level"`
	JupiterDyrpcTestTimeout                  string   `json:"jupiter.dyrpc.test.timeout"`
	JupiterEtcdv3RegisterTimeout             string   `json:"jupiter.etcdv3.register.timeout"`
	JupiterDyrpcPullerAddrs                  []string `json:"jupiter.dyrpc.puller.addrs"`
	JupiterBigmapTestSweepInterval           string   `json:"jupiter.bigmap.test.sweepInterval"`
	JupiterMongoTestPoolLimit                int      `json:"jupiter.mongo.test.poolLimit"`
	JupiterRestyTestAddr                     string   `json:"jupiter.resty.test.addr"`
	JupiterRestyTestRetryWaitTime            string   `json:"jupiter.resty.test.retryWaitTime"`
	TimeoutStatus                            int      `json:"timeout.status"`
	JupiterRocketmqTestConsumerCapacity      int      `json:"jupiter.rocketmq.test.consumer.capacity"`
	JupiterRocketmqTestConsumerAddr          []string `json:"jupiter.rocketmq.test.consumer.addr"`
	AppMetricInterval                        string   `json:"app.metric.interval"`
	JupiterEtcdv3ConfigserverTimeout         string   `json:"jupiter.etcdv3.configserver.timeout"`
	JupiterRedixTestStubSlavesAddr           []string `json:"jupiter.redix.test.stub.slaves.addr"`
	AppRegistryEtcdEndpoints                 []string `json:"app.registry.etcd.endpoints"`
	JupiterDyrpcEtcdRegisterTTL              string   `json:"jupiter.dyrpc.etcd.registerTTL"`
	JupiterEtcdv3ConfigserverEndpoints       []string `json:"jupiter.etcdv3.configserver.endpoints"`
	JupiterRestyTestEnableAccessLog          bool     `json:"jupiter.resty.test.enableAccessLog"`
	AppMode                                  string   `json:"app.mode"`
	JupiterRestyTestEnableTrace              bool     `json:"jupiter.resty.test.enableTrace"`
	JupiterMysqlGRPCAdminConnMaxLifetime     string   `json:"jupiter.mysql.gRPCAdmin.connMaxLifetime"`
	JupiterRedixTestStubMaxActive            int      `json:"jupiter.redix.test.stub.maxActive"`
	JupiterMongoTestDsn                      string   `json:"jupiter.mongo.test.dsn"`
	JupiterLeveldbTestFilePath               string   `json:"jupiter.leveldb.test.FilePath"`
	ServerGovernPort                         int      `json:"server.govern.port"`
	ServerGrpcPort                           int      `json:"server.grpc.port"`
	JupiterRocketmqTestConsumerRate          int      `json:"jupiter.rocketmq.test.consumer.rate"`
	JupiterEtcdv3SentinelEndpoints           []string `json:"jupiter.etcdv3.sentinel.endpoints"`
	JupiterDyrpcEtcdAddrs                    []string `json:"jupiter.dyrpc.etcd.addrs"`
	JupiterMysqlGRPCAdminMaxOpenConns        int      `json:"jupiter.mysql.gRPCAdmin.maxOpenConns"`
	ServerHTTPPort                           int      `json:"server.http.port"`
	JupiterGrpcTestAddr                      string   `json:"jupiter.grpc.test.addr"`
	JupiterRocketmqTestProducerAddr          []string `json:"jupiter.rocketmq.test.producer.addr"`
	JupiterEtcdv3SentinelTimeout             string   `json:"jupiter.etcdv3.sentinel.timeout"`
	JupiterRocketmqTestConsumerTopic         string   `json:"jupiter.rocketmq.test.consumer.topic"`
	JupiterDyrpcTestGroupid                  int      `json:"jupiter.dyrpc.test.groupid"`
	JupiterBigmapTestBucketSize              int      `json:"jupiter.bigmap.test.bucketSize"`
	JupiterRedixTestStubReadTimeout          string   `json:"jupiter.redix.test.stub.readTimeout"`
}
