
[app]
  appurl = ""
  mode = "prod"
  name = "juno"
  token = "123456"
  secretKey = "ASDFASDFASDF"

  [app.registry]

    [app.registry.etcd]
      endpoints = ["127.0.0.1:2379"]
      timeout = "2s"


[configure]
  dir = "/tmp/www/server"
  prefix = "juno-agent"

  [configure.agent]
    port = 50010


[jupiter.logger.default]
    debug = true          # 是否在命令行输出
    enableConsole = true  # 是否按命令行格式输出
    level = "debug"


[session]
  maxAge = 172800
  secret = "ldfgoqnf935nvav34"
  type = ""


#################################### Server ##############################
[server.http]
    # The ip address to bind to, empty will bind to all interfaces
    host = "0.0.0.0"
    # The http port to use
    port = 50002
    domain = "localhost"
    # enable gzip
    enableGzip = false
[server.govern]
    # The ip address to bind to, empty will bind to all interfaces
    host = "0.0.0.0"
    # The http port to use
    port = 50003
    domain = "localhost"
    # enable gzip
    enableGzip = false
#################################### Database ##############################
[database]
    enable = true
    connMaxLifetime = "300s"
    debug = true
    dsn = "root:root@tcp(127.0.0.1:3306)/juno?charset=utf8&parseTime=True&loc=Local&readTimeout=1s&timeout=1s&writeTimeout=3s"
    level = "panic"
    maxIdleConns = 50
    maxOpenConns = 100

[grafanaProxy]
    enable = true
    name = "grafana"

#################################### Proxy ##############################
[[clientProxy]]
  name = "live.cn-wuhan-guanggu-f1"
  
  [clientProxy.stream]
    enable = true
    proxyAddr = ["127.0.0.1:50001"]

  [clientProxy.etcd]
    enable = true
    endpoints = ["127.0.0.1:52379"]
    timeout = 3

  [clientProxy.http]
    listenAddr = "127.0.0.0:8888"
    disableKeepAlives = true
    maxIdelPerHost = 1
    maxIdleConns = 10
    timeout = 100

[pprof]
    path = "."

[auth]
    # Login cookie name
    loginCookieName = "juno_session"
    # The lifetime (days) an authenticated user can be inactive before being required to login at next visit. Default is 7 days.
    # 接口授权用户
    loginMaximumInactiveLifetimeDays = 7
    # The maximum lifetime (days) an authenticated user can be logged in since login time before being required to login. Default is 30 days.
    # 页面登录用户
    loginMaximumLifetimeDays = 30
    # How often should auth tokens be rotated for authenticated users when being active. The default is each 10 minutes.
    # 刷新时间
    tokenRotationIntervalMinutes = 10
    # Set to true to disable (hide) the login form, useful if you use OAuth
    disableLoginForm = false
    # Set to true to disable the signout link in the side menu. useful if you use auth.proxy
    disableSignoutMenu = false
    # URL to redirect the user to after sign out
    signoutRedirectUrl = ""
    # Set to true to attempt login with OAuth automatically, skipping the login screen.
    # This setting is ignored if multiple OAuth providers are configured.
    oauthAutoLogin = false
    # OAuth state max age cookie duration. Defaults to 60 seconds.
    oauthStateCookieMaxAge = 60
    # limit of api_key seconds to live before expiration
    apiKeyMaxSecondsToLive = -1


#################################### Anonymous Auth ######################
[auth.anonymous]
    # enable anonymous access
    enabled = false
    # specify organization name that should be used for unauthenticated users
    orgName = "Main Org."
    # specify role for unauthenticated users
    orgRole = "Viewer"
    # mask the Grafana version number for unauthenticated users
    hideVersion = false

#################################### Github Auth #########################
[auth.github]
    enable = true
    allowSignUp = true
    clientId = "a6633e5544e60bd2574e"
    clientSecret = "7c6f51d97fc93d5d575ebd13115b20f397807549"
    scopes = ["user:email","read:org"]
    authUrl = "https://github.com/login/oauth/authorize"
    tokenUrl = "https://github.com/login/oauth/access_token"
    apiUrl = "https://api.github.com/user"
    allowedDomains = []
    teamIds = []
    allowedOrganizations = []
