basePath: /
definitions:
  main.HTTPError:
    properties:
      message:
        type: string
      status:
        type: string
    type: object
  main.Item:
    properties:
      id:
        type: string
    type: object
host: localhost:3000
info:
  contact:
    email: youremail@provider.com
    name: API Support
  description: This is a sample swagger for Fiber
  title: Fiber Example API
  version: "1.0"
paths:
  /api/item/{id}:
    get:
      consumes:
      - application/json
      description: Get an item by its ID
      operationId: get-item-by-int
      parameters:
      - description: Item ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.Item'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HTTPError'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/main.HTTPError'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HTTPError'
      summary: Get an item
      tags:
      - Item
swagger: "2.0"
