{
 "title": "Overview",
 "tags": [ "prometheus" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "机房", "query": "prometheus" },
   { "name": "appname", "label": "应用名", "query": "label_values(go_info{},job)" },
   {
    "name": "instance",
    "label": "实例",
    "query": "label_values(go_info{job=~'$appname'},instance)"
   },
   {
    "name": "summarize",
    "query": "5s,10s,30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "SOA 服务响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg(histogram_quantile(0.75,rate(jupiter_server_handle_seconds_bucket{job=\"$appname\"}[1m])>0)*1000)by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "75th Percentile",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "p95" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "95th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p98" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "98th Percentile" ], "type": "alias" }
      ],
      [
       { "params": [ "p99" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "99th Percentile" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "avg(histogram_quantile(0.95,rate(jupiter_server_handle_seconds_bucket{job=\"$appname\"}[1m])>0)*1000)by(job)",
     "legendFormat": "95th Percentile"
    },
    {
     "expr": "avg(histogram_quantile(0.99,rate(jupiter_server_handle_seconds_bucket{job=\"$appname\"}[1m])>0)*1000)by(job)",
     "legendFormat": "99th Percentile"
    }
   ]
  },
  {
   "title": "SOA 服务QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(irate(jupiter_server_handle_seconds_count{job=\"$appname\"}[1m]))by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1 min rate",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "sum(irate(jupiter_server_handle_seconds_count{job=\"$appname\"}[5m]))by(job)",
     "legendFormat": "5 min rate"
    },
    {
     "expr": "sum(irate(jupiter_server_handle_seconds_count{job=\"$appname\"}[15m]))by(job)",
     "legendFormat": "15 min rate"
    }
   ]
  },
  {
   "title": "SOA 服务成功率",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(rate(jupiter_server_handle_total{code=\"OK\",job=\"$appname\"}[1m]))by(job)/sum(rate(jupiter_server_handle_total{job=\"$appname\"}[1m]))by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "异常QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(irate(jupiter_server_handle_total{code!=\"OK\",job=\"$appname\"}[1m]))by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "1 min rate",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    },
    {
     "expr": "sum(irate(jupiter_server_handle_total{code!=\"OK\",job=\"$appname\"}[5m]))by(job)",
     "legendFormat": "5 min rate"
    },
    {
     "expr": "sum(irate(jupiter_server_handle_total{code!=\"OK\",job=\"$appname\"}[15m]))by(job)",
     "legendFormat": "15 min rate"
    }
   ]
  },
  {
   "title": "依赖服务QPS",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "sum(irate(jupiter_client_handle_seconds_count{job=\"$appname\"}[5m]))by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  },
  {
   "title": "依赖服务响应时间",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$col",
     "expr": "avg(histogram_quantile(0.99, irate(jupiter_client_handle_seconds_bucket{job=\"$appname\"}[1m])>0)*1000)by(job)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{job}}",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "1 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate5m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "5 min rate" ], "type": "alias" }
      ],
      [
       { "params": [ "rate15m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "15 min rate" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "env", "operator": "=~", "value": "/^$environment$/" },
      { "condition": "AND", "key": "app", "operator": "=~", "value": "/^$application$/" }
     ]
    }
   ]
  }
 ]
}